// This file is auto-generated by @hey-api/openapi-ts

import type { UseMutationOptions } from '@tanstack/react-query';

import { type Options, predictGlucosePredictPost } from '../sdk.gen';
import type { PredictGlucosePredictPostData, PredictGlucosePredictPostError, PredictGlucosePredictPostResponse } from '../types.gen';

/**
 * Predict Glucose
 *
 * Primary endpoint: Takes raw input, extracts features via LLM, predicts glucose
 * via ML model, classifies risk, and triggers emergency alerts if necessary.
 */
export const predictGlucosePredictPostMutation = (options?: Partial<Options<PredictGlucosePredictPostData>>): UseMutationOptions<PredictGlucosePredictPostResponse, PredictGlucosePredictPostError, Options<PredictGlucosePredictPostData>> => {
    const mutationOptions: UseMutationOptions<PredictGlucosePredictPostResponse, PredictGlucosePredictPostError, Options<PredictGlucosePredictPostData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await predictGlucosePredictPost({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
